events {}

http {

  upstream haproxy_backend {
    server haproxy:8080;
  }

  limit_req_zone $binary_remote_addr zone=ws_limit:10m rate=5r/s;

  server {
    listen 80;

    location /ws/ {

      limit_req zone=ws_limit burst=10;

      proxy_pass http://haproxy_backend;

      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "Upgrade";

      proxy_set_header Host $host;

      proxy_read_timeout 3600;
      proxy_send_timeout 3600;
    }
  }
}
